name: "CI"

on:
  push:
    branches: [ main ]

jobs:
  build:
    defaults:
      run:
        working-directory: "CitrucelBot"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.x

      - name: .NET Publish
        run: dotnet publish --configuration=Release

  terraform:
    needs: build
    defaults:
      run:
        working-directory: "terraform"

    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_bot_token: ${{ secrets.TF_VAR_BOT_TOKEN }}
      TF_VAR_chat_id: ${{ secrets.TF_VAR_CHAT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out plan

      - name: Terraform Apply
        run: terraform apply -auto-approve "plan"
