name: .NET Build

on:
  push:
    branches:
      - main

    paths:
      - "CitrucelBot/**"

jobs:
  build:
    defaults:
      run:
        working-directory: "CitrucelBot"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Build .NET
        run: dotnet build --configuration=Release
