name: "Terraform"

defaults:
  run:
    working-directory: "terraform"
on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      TF_VAR_bot_token: ${{ secrets.TF_VAR_BOT_TOKEN }}
      TF_VAR_chat_id: ${{ secrets.TF_VAR_CHAT_ID }}

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
